### ISSUE TITLE
Hugging Face里没有vocab.txt文件

### ISSUE THREAD

**Issue by Echoleung** [WENGSYX/CirBERTa#1]
请问是用的什么vocab.txt文件呢

**Comment by WENGSYX** [comment]
请不要使用transformers.BertTokenizer去加载词表
请使用-> transformers.AutoTokenizer.from_pretrained("WENGSYX/CirBERTa-Chinese-Base")

**Comment by nlp4whp** [comment]
> transformers.AutoTokenizer.from_pretrained("WENGSYX/CirBERTa-Chinese-Base")

能麻烦您提供下transformers的版本么，我会遇到下面的错，但确实能在huggingface.co看到您的项目，所以我怀疑是自己版本的问题

```
OSError: Can't load config for 'WENGSYX/CirBERTa-Chinese-Base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'WENGSYX/CirBERTa-Chinese-Base' is the correct path to a directory containing a config.json file
```
