### ISSUE TITLE
请问训练语料是通用语料还是医学领域语料？

### ISSUE THREAD

**Issue by lwb69** [WENGSYX/CirBERTa#4]
感谢回答，因为看一些报导写的是医学语料这边写的是通用语料，所以想请问一下。。。如果是医学领域语料请问使用哪些医学语料?是否使用了临床电子病历？

**Comment by WENGSYX** [comment]
开源的是通用训练的。而CBLUE排行榜上使用的模型，是使用了额外的医学语料进行继续预训练（大致包括，医患对话，医疗科普，医疗论文，医学教科书等内容）。
